version: "3.7"
services:
  poc-quarkus-kotlin:
    container_name: poc-quarkus-kotlin
    depends_on:
      - database-poc-quarkus-kotlin
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "8080:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database-poc-quarkus-kotlin:5432/postgres
  database-poc-quarkus-kotlin:
    container_name: database-poc-quarkus-kotlin
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  database-poc-quarkus-kotlin-test:
    container_name: database-poc-quarkus-kotlin-test
    image: postgres:12.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
